### ISSUE TITLE
distplot

### ISSUE THREAD

**Issue by LeanderK** [santosjorge/cufflinks#103]
i am missing a distribution-plot similiar to seaborn (https://seaborn.pydata.org/generated/seaborn.distplot.html). I use it all the time!
I would expect it to not be that hard, looks like it's already there https://plot.ly/python/distplot/.

**Comment by jpoles1** [comment]
Looks doable. I can try and tackle this as well @santosjorge. 

Just like with #50 this plot seems to require figure factory. @santosjorge I'm not sure how you wanted to handle this sorta plot, given you don't seem to use any other figure factory plots, and they produce a slightly different output (a whole figure rather than data/layout). I'll try and get a pull request ready for violin sometime soon, and we can discuss implementation there?

**Comment by santosjorge** [comment]
Thank you @jpoles1 for offering to help!
Actually figure factory is already used across all subplots and financial (candle/ohlc) charts. 
Let me take a stab at the distplot one - and then would be more than happy to get some help with the violin (#50) one.

**Comment by jpoles1** [comment]
Sounds good, let me know what I can do to help!

**Comment by santosjorge** [comment]
This has been added to 0.13.1
See
`cf.help('distplot')`

**Comment by IvoMerchiers** [comment]
Running the code provide in Examples for distplot gives the following error:
`AttributeError: 'Layout' object has no attribute 'get'`
Should I open a new issue for that?
