### ISSUE TITLE
Reuse saved in config file colorscale value

### ISSUE THREAD

**Issue by cooperok** [santosjorge/cufflinks#91]
Hi. There is a property 'colorscale' in set_config_file method. And I think it is expected that it should be used in iplot method, but it's not. I wanted to fix that but don't know how to implement it best

I would expect something like this in plotlytools.py (line 686)
```
if colorscale is None:
    config_colorscale = auth.get_config_file()['colorscale']
    colorscale=config_colorscale if config_colorscale is not None else theme_config['colorscale'] if 'colorscale' in theme_config else 'dflt'
```
but there is a problem, 'colorscale' always exists in config_file. As one of possible solutions I see changing method set_config_file to save colorscale even if it's None. 
So logic is next, if you want to remember your colorscale call method:
```
cufflinks.set_config_file(colorscale='polar')
```
if you want to use default colorscale call method:
```
cufflinks.set_config_file()
```

But such approach has one minus. Users who alredy have used cufflinks have their config file with filled colorscale. And it's property will be used always.
For example, someone has set theme to 'ggplot' but colorscale not. Then he has default colorscale 'dflt' in config file. By current logic colorscale is selected from theme config and is expected to be 'ggplot' but with new logic it will be 'dflt' which I think is not accepted.
Maybe somehow reset that value in config file?

**Comment by santosjorge** [comment]
Mm. I see the issue. I did mess it up on that one! 
Ok, what do you think of the following:

1. We create a copy of the `'dflt'` scale and we give it another name (_original_?)
2. We treat `'dflt'` as if it was None (for backward compatibility)- so if `config_file['colorscale']='dflt'` then we assume nothing has been set by the user - and then we load the `theme` scale. 
3. Change the theme's definitions to use `colorscale=original` instead. 
4. Change the config_file to have `colorscale = None` going forward

And then we apply the code suggested above, slightly modified:

```
if colorscale is None:
    config_colorscale = auth.get_config_file()['colorscale']
    colorscale=config_colorscale if config_colorscale is not in (None,'dflt') else theme_config['colorscale'] if 'colorscale' in theme_config else 'original'
```

What do you think?

Otherwise the value can be reset, but some people my complain that now new settings are being written on disk. 

Let me know know your thoughts.

**Comment by cooperok** [comment]
I think that is enough for expected behavior for everyone. Even for those who set colorscale to 'dflt' deliberately because they still had to pass it to iplot method if they used theme with colorscale different than 'dflt'
