### ISSUE TITLE
The chart becomes discontinuous when use real trading data

### ISSUE THREAD

**Issue by xmduhan** [santosjorge/cufflinks#96]
This is fine!
``` python
df = cf.datagen.ohlc()
qf = cf.QuantFig(df, title='First Quant Figure',legend='top',name='GS')
qf.iplot()
```
Real trading data , the time is discontinuous, but should be display as continuous chart.
``` python
df = cf.datagen.ohlc()
df['day'] = df.index.dayofweek
df = df[df['day'] < 5]
qf = cf.QuantFig(df, title='First Quant Figure',legend='top',name='GS')
qf.iplot()
```
How can I play with QuantFig to make chart continuous?

**Comment by santosjorge** [comment]
Hi @xmduhan - yes this is a long standing open issue with Plotly itself. 
You can follow that issue here: https://github.com/plotly/plotly.py/issues/529
There is also a suggested workaround (set `layout['xaxis']['type']='category'`) - although I am not a big fan of the outcome that gives (as the axis becomes numerical rather than datetime). 

I would rather not try to hack this from cufflinks itself.

**Comment by xmduhan** [comment]
Ok, Thank you!
